name: Test & Publish

on: [push, pull_request]

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install npm dependencies
        run: npm i

      - name: Install grunt cli
        run: npm i -g grunt-cli

      - name: Run tests
        run: grunt test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}